### ISSUE TITLE
Random redirect to empty page from KinoExplorer Data Transform Smart Cell

### ISSUE THREAD

**Issue by jzimmerman135** [livebook-dev/kino_explorer#156]
The "assign to" input box redirects me to a junk link if I hit enter.
Specifically I get sent to:
http://localhost:63081/iframe/v5.html?data_frame=processes&assign_to=

I am on chromium with mac m1

# Minimum reproducible example:

1. Create a cell with
```
keys = [:registered_name, :initial_call, :reductions, :stack_size]

processes =
  for pid <- Process.list(),
      info = Process.info(pid, keys),
      do: info

Kino.DataTable.new(processes)
```
2. Add a data transform smart cell
3. Focus the "Assign To" box, and hit enter

Fan note:
---------

I gotta say this is so freaking fantastic!!!!!

I actually started my own little project that tried to do some macro cells/smart cells before realizing how far livebooks have come. I definitely want to start contributing, I am wildly impressed.

**Comment by cristineguadelupe** [comment]
Thanks @jzimmerman135!
Fixed on #157
