### ISSUE TITLE
Make columns draggable

### ISSUE THREAD

**Issue by clayscode** [livebook-dev/kino_explorer#158]
A nice to have feature would be the ability to rearrange the order of columns. Either via the table itself, or the ability to rearrange the tags in the "Select" action. It's possible to re-arrange the columns using "Select" by just adding the tags in the order you'd like, but if you forget a tag or would like to change the order, you have to delete every tag up until the place you wanted to change the order. 

For instance:

<img width="1255" alt="Screen Shot 2024-03-25 at 7 20 14 PM" src="https://github.com/livebook-dev/kino_explorer/assets/16871737/6fea4b30-e8ad-4f8a-9645-364502524713">

Using the select action makes it possible to set the order of columns. However if I'd like to change the order of Embarked and PassengerID, I'd have to delete all the tags and then re-add them in the order I'd like. This is especially cumbersome when you have lots of columns.   

In my mind, it seems simpler to make the multiselect field draggable using the draggable component (trying to figure out how, but haven't been successful so far), but if it would be easier to add the draggable component to the columns themselves, that would work as well.

**Comment by josevalim** [comment]
@clayscode a pull request would be welcome!
