### ISSUE TITLE
DataTransformCell crashes due to incompatibility with support for datetimes with timezones added in Explorer 0.8.3

### ISSUE THREAD

**Issue by sesamzoo** [livebook-dev/kino_explorer#169]
The following change described in Explorer's [v0.8.3 changelog](https://hexdocs.pm/explorer/changelog.html#v0-8-3-2024-06-10)

> Add new data type for datetimes with timezones: `{:datetime, precision, time_zone}` The old dtype is now `{:naive_datetime, precision}`.

lets [`DataTransformCell.normalize_dtypes`](https://github.com/livebook-dev/kino_explorer/blob/v0.1.20/lib/kino_explorer/data_transform_cell.ex#L1003-L1024) crash with "1st argument: not an atom" from `Atom.to_string(v)` in the last pattern

```elixir
    |> Enum.map(fn
      # TODO: {:datetime, _} is removed on v0.9+
      {k, {:datetime, :millisecond}} -> {k, "datetime[ms]"}
      {k, {:datetime, :microsecond}} -> {k, "datetime[μs]"}
      {k, {:datetime, :nanosecond}} -> {k, "datetime[ns]"}
      {k, {:naive_datetime, :millisecond}} -> {k, "datetime[ms]"}
      {k, {:naive_datetime, :microsecond}} -> {k, "datetime[μs]"}
      {k, {:naive_datetime, :nanosecond}} -> {k, "datetime[ns]"}
      {k, {:f, 32}} -> {k, "float"}
      {k, {:f, 64}} -> {k, "float"}
      {k, {:s, 8}} -> {k, "integer"}
      {k, {:s, 16}} -> {k, "integer"}
      {k, {:s, 32}} -> {k, "integer"}
      {k, {:s, 64}} -> {k, "integer"}
      {k, {:u, 8}} -> {k, "integer"}
      {k, {:u, 16}} -> {k, "integer"}
      {k, {:u, 32}} -> {k, "integer"}
      {k, {:u, 64}} -> {k, "integer"}
      {k, {:list, _}} -> {k, "list"}
      {k, {:struct, _}} -> {k, "struct"}
      {k, v} -> {k, Atom.to_string(v)}
    end)
```

when the data frame contains f.i. a column with a datetime with µs precision in UTC.

**Comment by josevalim** [comment]
Could you very kindly submit a PR? Then I can cut a new release. :)

**Comment by sesamzoo** [comment]
> Could you very kindly submit a PR? Then I can cut a new release.

@josevalim, that would require a fix which I don't have. ;) I just started using LiveBook and (Kino) Explorer two days ago.

At first glance it looks like this is just a matter of "map the datatype to a string used for presentation". I'll see if I can find the time to confirm that and create a PR.

If anyone more experienced is faster with a PR, I won't be mad, though.

**Comment by josevalim** [comment]
> At first glance it looks like this is just a matter of "map the datatype to a string used for presentation". I'll see if I can find the time to confirm that and create a PR.

@sesamzoo yes, exactly, that should be all that is necessary!

Probably we can print it as `datetime[μs, #{zone}]`.

**Comment by josevalim** [comment]
Can you please try the main branch and let us know if it works? Thank you :heart:

**Comment by sesamzoo** [comment]
Data transform cell for data frame with UTC datetimes work with the main branch (4f79ece) and Explorer 0.8.3.
Thanks a lot, @josevalim.

**Comment by josevalim** [comment]
New version released!
