### ISSUE TITLE
Does not support kino 0.14.0

### ISSUE THREAD

**Issue by cmeon** [livebook-dev/kino_explorer#172]
Tried installing kino_explorer with kino 0.14.0 but it complains that it is only restricted to 0.13.0.

```
Resolving Hex dependencies...
Resolution completed in 0.035s
Because kino_explorer >= 0.1.20 depends on kino ~> 0.13.0 and your app depends on kino ~> 0.14.0, kino_explorer >= 0.1.20 is forbidden.
So, because your app depends on kino_explorer ~> 0.1.22, version solving failed.
```

**Comment by philss** [comment]
@cmeon you can try to override the `:kino` version in your `mix.exs` file or in your `Mix.install/2` call. To do that, just add `{:kino, ">= 0.14.0", override: true}`.
We will check if it's possible to relax the version requirement and we can launch a patch version.
