### ISSUE TITLE
Support Infinities in DataFrames/Series

### ISSUE THREAD

**Issue by msluszniak** [livebook-dev/kino_explorer#48]
Currently, when a series or data frame contains infinities there is an error.

for input 
```elixir
DF.new(a: Nx.tensor([:infinity], type: {:f, 64}))
```
and
```elixir
S.from_tensor(Nx.tensor([:infinity], type: {:f, 64}))
```

15:35:11.764 [error] ** (MatchError) no match of right hand side value: {:error, {:badarg, [{Explorer.PolarsBackend.Native, :s_mean, [#Explorer.PolarsBackend.Series<
         shape: (1,)
         Series: 'series' [f64]
         [
         	inf
         ]
       >], []}, {Explorer.PolarsBackend.Shared, :apply_series, 3, [file: 'lib/explorer/polars_backend/shared.ex', line: 23]}, {Kino.Explorer, :"-summaries/1-fun-0-", 2, [file: 'lib/kino/explorer.ex', line: 94]}, {:maps, :fold_1, 3, [file: 'maps.erl', line: 411]}, {Kino.Explorer, :summaries, 1, [file: 'lib/kino/explorer.ex', line: 89]}, {Kino.Explorer, :init, 1, [file: 'lib/kino/explorer.ex', line: 42]}, {Kino.Table, :init, 2, [file: 'lib/kino/table.ex', line: 63]}, {Kino.JS.Live.Server, :call_init, 3, [file: 'lib/kino/js/live/server.ex', line: 76]}]}}
    (kino 0.9.0) lib/kino/js/live.ex:326: Kino.JS.Live.new/2
    (kino_explorer 0.1.2) lib/kino_explorer.ex:9: Kino.Render.Explorer.Series.to_livebook/1
    lib/livebook/runtime/evaluator/default_formatter.ex:41: Livebook.Runtime.Evaluator.DefaultFormatter.to_output/1
    lib/livebook/runtime/evaluator.ex:464: Livebook.Runtime.Evaluator.continue_do_evaluate_code/5
    lib/livebook/runtime/evaluator.ex:326: Livebook.Runtime.Evaluator.loop/1
    (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

**Comment by josevalim** [comment]
The root cause comes from Explorer, so we need to fix it there first, but we need to make sure we show it properly here too. :)
