### ISSUE TITLE
Allow filtering by mean, median, and quantile

### ISSUE THREAD

**Issue by josevalim** [livebook-dev/kino_explorer#54]
We should allow filtering by the mean, median, and quantile.

For example, if I want to filter a dataset for values that above its mean, we could do:

    Filter by      operator       value
    septal_length  greater than   mean

UI wise, this has a couple issues:

1. value is a number, how could we input the mean? Perhaps a select?

2. for quantiles, we would need a fourth input specifying the quantile but that's likely too complex, we could instead provide predefined quantiles for 10%, 20%, ..., 90%

**Comment by cristineguadelupe** [comment]
A datalist might solve both
