### ISSUE TITLE
Top statistics not clear when majority is null

### ISSUE THREAD

**Issue by Hanspagh** [livebook-dev/kino_explorer#70]
First of all very excited to see this coming to livebook.

It took me a bit of time to release why the `top` statistics were empty for the last column in the screenshot, maybe it is just me.  
I also think we could have min/max statistics for datetime and date instead of top.
I would be happy to help fixing this, if needed 

![image](https://user-images.githubusercontent.com/1024416/232525999-185b80b8-c23a-43ef-90cd-8734062e1bf5.png)

**Comment by josevalim** [comment]
I think there are two issues here. One is that we are showing null as top and we should not. Would like to send a PR for that?

the other is to use min/max, but we should probably have a separate discussion for that one. :)

**Comment by cristineguadelupe** [comment]
> One is that we are showing null as top and we should not.
Maybe we should, but obviously not the empty string!

**Comment by josevalim** [comment]
@cristineguadelupe we already show the number of nulls, which together with the number of top entries (besides null) will be enough to distingish if null is actually the most frequent. For example, if this summary said something like:

    top: 2020-01-01
    top_freq: 324
    nulls: 189119

It will be pretty clear nulls is more frequent, so IMO we should show the first non-null top. (also we should rename `top_freq:` to `top freq:` :))

**Comment by Hanspagh** [comment]
> I think there are two issues here. One is that we are showing null as top and we should not. Would like to send a PR for that?

Sure
